/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1/analyze": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Analyze a product URL and return a site profile.
     * @description Fetches the URL (chromedp for SPAs, colly for static pages), extracts the value
     *     proposition, and classifies industry and audience. The resulting SiteProfile is
     *     the input to generation.
     */
    post: operations["analyzeSite"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/generate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Generate three pricing-page variations (SSE stream).
     * @description Generates three variations in parallel, each with a distinct strategy, and streams
     *     progress as Server-Sent Events. The stream emits StreamChunk events until a
     *     terminal `done` (or `error`) event. The completed Generation is also retrievable
     *     afterwards via GET /v1/generations/{id}.
     */
    post: operations["generateVariations"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/generations/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Fetch a previously produced generation. */
    get: operations["getGeneration"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/export/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Export one variation of a generation in the requested format.
     * @description Renders a single variation as a JSX component, standalone HTML, or a Stripe
     *     Pricing Table JSON configuration. No Stripe API calls are made; only config is
     *     produced.
     */
    post: operations["exportVariation"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/healthz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liveness and readiness probe. */
    get: operations["healthCheck"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AnalyzeRequest: {
      /**
       * Format: uri
       * @description The product URL to analyze.
       * @example https://example.com
       */
      url: string;
    };
    SiteProfile: {
      /** Format: uri */
      url: string;
      title: string;
      /** @description One-to-two sentence summary of what the product offers. */
      valueProposition: string;
      /** @description Classified industry, e.g. "developer-tools", "e-commerce". */
      industry: string;
      audience: components["schemas"]["Audience"];
      /** @description Salient terms extracted from the page. */
      keywords?: string[];
      /**
       * @description Which scraper handled the page.
       * @enum {string}
       */
      sourceType: "spa" | "static";
      /** Format: date-time */
      analyzedAt: string;
    };
    Audience: {
      /** @description e.g. "SaaS founders", "enterprise IT", "indie developers". */
      segment: string;
      /**
       * @description Price/technical sophistication of the audience.
       * @enum {string}
       */
      sophistication: "low" | "medium" | "high";
      /** @enum {string} */
      pricePosition?: "budget" | "mid_market" | "premium";
    };
    /**
     * @description The psychological pricing strategy applied to a variation.
     * @enum {string}
     */
    PricingStrategy: "anchor" | "freemium" | "value_based";
    GenerateRequest: {
      siteProfile: components["schemas"]["SiteProfile"];
      /**
       * @description Strategies to generate. Defaults to all three when omitted. Duplicates are
       *     rejected.
       */
      strategies?: components["schemas"]["PricingStrategy"][];
      /**
       * @description ISO 4217 currency code for generated prices.
       * @default USD
       */
      currency: string;
    };
    Generation: {
      /** Format: uuid */
      id: string;
      /** Format: uri */
      sourceUrl: string;
      siteProfile?: components["schemas"]["SiteProfile"];
      /** @enum {string} */
      status: "pending" | "streaming" | "completed" | "failed";
      variations: components["schemas"]["Variation"][];
      /** Format: date-time */
      createdAt: string;
    };
    Variation: {
      /** Format: uuid */
      id: string;
      strategy: components["schemas"]["PricingStrategy"];
      headline: string;
      subheadline?: string;
      tiers: components["schemas"]["PricingTier"][];
      /** @description Why this strategy fits the analyzed audience. */
      rationale?: string;
    };
    PricingTier: {
      /** @description e.g. "Free", "Pro", "Enterprise". */
      name: string;
      price: components["schemas"]["Price"];
      tagline?: string;
      features: string[];
      /** @description Call-to-action label, e.g. "Start free". */
      cta?: string;
      /**
       * @description Whether this tier is visually emphasized as the recommended plan.
       * @default false
       */
      highlighted: boolean;
      /** @description Optional badge text, e.g. "Most popular". */
      badge?: string;
    };
    Price: {
      /** @description Amount in the currency's minor unit (e.g. cents). 0 means free. */
      amount: number;
      currency: string;
      /** @enum {string} */
      interval: "one_time" | "monthly" | "yearly";
      /** @description Overrides the rendered price, e.g. "Contact us". */
      customLabel?: string;
    };
    /**
     * @description One event in the generation SSE stream. `type` discriminates the payload:
     *     - `generation_started`: carries `generationId`.
     *     - `variation_started`: a variation began; carries `strategy`.
     *     - `token`: an incremental text delta for a variation; carries `strategy`, `delta`.
     *     - `variation_completed`: a finished variation; carries `variation`.
     *     - `done`: terminal success; carries the full `generation`.
     *     - `error`: terminal failure; carries `problem`.
     */
    StreamChunk: {
      /** @enum {string} */
      type:
        | "generation_started"
        | "variation_started"
        | "token"
        | "variation_completed"
        | "done"
        | "error";
      /** Format: uuid */
      generationId?: string;
      strategy?: components["schemas"]["PricingStrategy"];
      delta?: string;
      variation?: components["schemas"]["Variation"];
      generation?: components["schemas"]["Generation"];
      problem?: components["schemas"]["Problem"];
    };
    ExportRequest: {
      /** Format: uuid */
      variationId: string;
      /** @enum {string} */
      format: "jsx" | "html" | "stripe";
    };
    ExportResult: {
      /** @enum {string} */
      format: "jsx" | "html" | "stripe";
      /** @description Suggested filename, e.g. "PricingSection.tsx". */
      filename: string;
      /** @description MIME type of the content, e.g. "text/plain". */
      contentType: string;
      /** @description The exported artifact as text (JSX, HTML, or Stripe config JSON). */
      content: string;
    };
    HealthStatus: {
      /** @enum {string} */
      status: "ok" | "degraded";
      /** @description Build version or git SHA. */
      version: string;
      /** @description Per-dependency health, keyed by dependency name. */
      checks?: {
        [key: string]: "ok" | "fail" | "skipped";
      };
    };
    /** @description RFC 7807 problem details. */
    Problem: {
      /**
       * Format: uri
       * @default about:blank
       */
      type: string;
      title: string;
      status: number;
      detail?: string;
      instance?: string;
      /** @description Correlation id for logs and traces. */
      traceId?: string;
    } & {
      [key: string]: unknown;
    };
  };
  responses: {
    /** @description The request was malformed. */
    BadRequest: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/problem+json": components["schemas"]["Problem"];
      };
    };
    /** @description The request was well-formed but semantically invalid. */
    UnprocessableEntity: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/problem+json": components["schemas"]["Problem"];
      };
    };
    /** @description The requested resource does not exist. */
    NotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/problem+json": components["schemas"]["Problem"];
      };
    };
    /** @description Rate limit exceeded. */
    TooManyRequests: {
      headers: {
        /** @description Seconds to wait before retrying. */
        "Retry-After"?: number;
        [name: string]: unknown;
      };
      content: {
        "application/problem+json": components["schemas"]["Problem"];
      };
    };
    /**
     * @description A generation with the same Idempotency-Key is already in progress. Wait for it to
     *     finish, then retry with the same key to get its result, or use a new key to start
     *     an unrelated generation.
     */
    Conflict: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/problem+json": components["schemas"]["Problem"];
      };
    };
    /** @description An unexpected error occurred. */
    InternalError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/problem+json": components["schemas"]["Problem"];
      };
    };
  };
  parameters: {
    /**
     * @description Client-supplied key to make generation idempotent. Repeating a request with the
     *     same key once the first has completed returns the same generation instead of
     *     producing a new one. A repeat request with the same key while the first is still
     *     in progress gets 409 Conflict instead of starting a second, redundant generation.
     *
     *     Omitting this header does not disable deduplication: the server derives an
     *     implicit key from the request's siteProfile, strategies, and currency, so two
     *     requests with identical content are deduplicated the same way even without a
     *     shared client-chosen key. A practical consequence: two different callers
     *     submitting the same public product URL with the same strategies can transparently
     *     receive the same generation, or a 409 if the first is still running, even though
     *     neither supplied an Idempotency-Key. See ADR-0010.
     */
    IdempotencyKey: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  analyzeSite: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AnalyzeRequest"];
      };
    };
    responses: {
      /** @description Site analyzed successfully. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SiteProfile"];
        };
      };
      400: components["responses"]["BadRequest"];
      422: components["responses"]["UnprocessableEntity"];
      429: components["responses"]["TooManyRequests"];
      500: components["responses"]["InternalError"];
      /** @description The target site could not be fetched or parsed. */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/problem+json": components["schemas"]["Problem"];
        };
      };
    };
  };
  generateVariations: {
    parameters: {
      query?: never;
      header?: {
        /**
         * @description Client-supplied key to make generation idempotent. Repeating a request with the
         *     same key once the first has completed returns the same generation instead of
         *     producing a new one. A repeat request with the same key while the first is still
         *     in progress gets 409 Conflict instead of starting a second, redundant generation.
         *
         *     Omitting this header does not disable deduplication: the server derives an
         *     implicit key from the request's siteProfile, strategies, and currency, so two
         *     requests with identical content are deduplicated the same way even without a
         *     shared client-chosen key. A practical consequence: two different callers
         *     submitting the same public product URL with the same strategies can transparently
         *     receive the same generation, or a 409 if the first is still running, even though
         *     neither supplied an Idempotency-Key. See ADR-0010.
         */
        "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GenerateRequest"];
      };
    };
    responses: {
      /**
       * @description An event stream of StreamChunk objects. Each SSE `data:` line contains one
       *     JSON-encoded StreamChunk. The stream ends with a chunk of type `done`.
       */
      200: {
        headers: {
          /** @description The id assigned to this generation, also emitted in the stream. */
          "X-Generation-Id"?: string;
          [name: string]: unknown;
        };
        content: {
          "text/event-stream": components["schemas"]["StreamChunk"];
        };
      };
      400: components["responses"]["BadRequest"];
      409: components["responses"]["Conflict"];
      422: components["responses"]["UnprocessableEntity"];
      429: components["responses"]["TooManyRequests"];
      500: components["responses"]["InternalError"];
    };
  };
  getGeneration: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The generation and its variations. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Generation"];
        };
      };
      404: components["responses"]["NotFound"];
      500: components["responses"]["InternalError"];
    };
  };
  exportVariation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The generation id. */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ExportRequest"];
      };
    };
    responses: {
      /** @description The exported artifact. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExportResult"];
        };
      };
      400: components["responses"]["BadRequest"];
      404: components["responses"]["NotFound"];
      500: components["responses"]["InternalError"];
    };
  };
  healthCheck: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Service is healthy. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthStatus"];
        };
      };
      /** @description Service is degraded or a dependency is unavailable. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthStatus"];
        };
      };
    };
  };
}
